#!/bin/bash

case `basename $1` in
    *.log)
        ;;
    .zshrc|.zprofile)
        pygmentize -O encoding=utf-8 -O style=colorful -l sh "$1"
        ;;
    .gitconfig|.gitignore|.editorconfig)
        pygmentize -O encoding=utf-8 -O style=colorful -l text "$1"
        ;;
    .eslintrc|.jshintrc)
        pygmentize -O encoding=utf-8 -O style=colorful -l json "$1"
        ;;
    Gemfile|Podfile)
        pygmentize -O encoding=utf-8 -O style=colorful -l ruby "$1"
        ;;
    *)
        head -n 1 "$1" | grep '#!/bin/bash\|#!/bin/sh' > /dev/null
        if [ "$?" -eq "0" ]; then
            pygmentize -O encoding=utf-8 -O style=colorful -l sh "$1"
        else
            pygmentize -O encoding=utf-8 -O style=colorful -g "$1"
        fi
        ;;
esac
